name: CI

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish
        uses: gikiapp/giki.action@v1.1.0
        with:
          token: ${{secrets.GIKI_TOKEN}}
